openapi: 3.0.1
info:
  description: A RESTful web service demo
  version: 1.0.0
  title: Demo OpenAPI 3.0 contract
paths:
  '/schema/{name}':
    get:
      summary: Find schema by name
      description: Returns specific schema by name
      operationId: getSchemaBySchemaName
      x-exegesis-controller: schemaController
      parameters:
        - name: name
          in: path
          description: Name of schema to use
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A Schema definition
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid status value
        default:
          description: Error
          content:
            application/json:
              schema:
                type: string
  '/multiply-by-2/{operand}':
    get:
      summary: Multiplies a supplied number by 2
      description: Returns double the number passed in
      operationId: getMultipleOf2
      parameters:
        - name: operand
          in: path
          description: Number that is to be multiplied by 2
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema: 
                $ref: "schema/multiply-by-2#"
        '400':
          description: Invalid operand
          content:
            application/json:
              schema: 
                $ref: "schema/response-error#"
        default:
          description: Error
          content:
            application/json:
              schema: 
                $ref: "schema/response-error#"
